version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.1

commands:
  npm:
    parameters:
      location:
        type: string
    steps:
      - restore_cache:
          keys:
            - npm-cache-<< parameters.location >>-{{checksum "<< parameters.location >>/package-lock.json"}}
            - npm-cache-<< parameters.location >>-
      - run:
          name: Install << parameters.location >> dependencies
          working_directory: << parameters.location >>
          command: npx npm@6.14 ci
      - save_cache:
          key: npm-cache-<< parameters.location >>-{{checksum "<< parameters.location >>/package-lock.json"}}
          paths:
            - ~/.npm
            - ~/.cache

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:14.15.2-browsers
      - image: mongo:4.2.5
    steps:
      - browser-tools/install-chrome
      - checkout
      - npm:
          location: frontend
      - run:
          name: REMOVE THIS TASK
          working_directory: frontend
          command: echo ABC; echo $SECRET_VARIABLE
      - run:
          name: Angular lint
          working_directory: frontend
          command: npm run lint
      - run:
          name: Angular build
          working_directory: frontend
          command: npm run build -- --progress=false
      - run:
          name: Angular test
          working_directory: frontend
          command: npm test -- --watch=false --browsers=ChromeHeadless --progress=false
      - npm:
          location: backend
      - run:
          name: BE build
          working_directory: backend
          command: npm run build
      - run:
          name: BE run
          working_directory: backend
          command: |
            TERMINATE=1 npm run start:dev
            TERMINATE=1 npm run start:prod
          environment:
            MONGO_URI: mongodb://localhost:27017/corona
      - run:
          name: Cypress
          working_directory: frontend
          command: npm run http & npm run cypress:ci
      - store_test_results:
          path: frontend/cypress/snapshots

workflows:
  version: 2
  test:
    jobs:
      - test
